COD distribution modification

diff --git a/.openshift/action_hooks/build b/.openshift/action_hooks/build
--- a/.openshift/action_hooks/build
+++ b/.openshift/action_hooks/build
@@ -35,13 +35,13 @@ if [ ! -d "${OPENSHIFT_DATA_DIR}downloads/current" ]
 then
   mkdir -p ${OPENSHIFT_TMP_DIR}drupal
 
-  echo "Download and install the latest stable version of Drupal"
+  echo "Download and install the latest stable version of COD distribution"
   echo
 
   mkdir -p ${OPENSHIFT_DATA_DIR}downloads
-  if ! $DRUSH dl drupal --destination=${OPENSHIFT_DATA_DIR}downloads --yes --default-major=7
+  if ! $DRUSH dl cod --destination=${OPENSHIFT_DATA_DIR}downloads --default-major=7
   then
-    echo "ERROR: Unable download and install Drupal."
+    echo "ERROR: Unable download and install COD distribution."
     exit 7
   fi
 
diff --git a/.openshift/action_hooks/deploy b/.openshift/action_hooks/deploy
--- a/.openshift/action_hooks/deploy
+++ b/.openshift/action_hooks/deploy
@@ -32,21 +32,22 @@ then
 
   #
   # Automatic installation only works with mysql.
+  # I will try with pgsql ... !
   #
-  if [ -z "$OPENSHIFT_MYSQL_DB_HOST" ]
+  if [ -z "$OPENSHIFT_POSTGRESQL_DB_HOST" ]
   then
       echo 1>&2
-      echo "Could not find mysql database. Please run:" 1>&2
-      echo "rhc cartridge add mysql -a $OPENSHIFT_APP_NAME" 1>&2
+      echo "Could not find pgsql database. Please run:" 1>&2
+      echo "rhc cartridge add pgsql -a $OPENSHIFT_APP_NAME" 1>&2
       echo "then make a sample commit (add whitespace somewhere) and re-push" 1>&2
       echo 1>&2
   fi
 
-  if [ -z "$OPENSHIFT_MYSQL_DB_HOST" ]
+  if [ -z "$OPENSHIFT_POSTGRESQL_DB_HOST" ]
   then
       exit 5
   fi
-  if [ -z "$OPENSHIFT_MYSQL_DB_PORT" ]
+  if [ -z "$OPENSHIFT_POSTGRESQL_DB_PORT" ]
   then
       exit 6
   fi
@@ -58,7 +59,7 @@ then
   echo
   echo "Creating a new Drupal site at ${DRUPAL_SITE_DIR}/default"
   echo
-  if ! $DRUSH site-install standard --site-name=${OPENSHIFT_APP_NAME} --account-pass=$admin_pwd --db-url=mysql://$OPENSHIFT_MYSQL_DB_USERNAME:$OPENSHIFT_MYSQL_DB_PASSWORD@$OPENSHIFT_MYSQL_DB_HOST:$OPENSHIFT_MYSQL_DB_PORT/$OPENSHIFT_APP_NAME --yes
+  if ! $DRUSH site-install standard --site-name=${OPENSHIFT_APP_NAME} --account-pass=$admin_pwd --db-url=pgsql://$OPENSHIFT_POSTGRESQL_DB_USERNAME:$OPENSHIFT_POSTGRESQL_DB_PASSWORD@$OPENSHIFT_POSTGRESQL_DB_HOST:$OPENSHIFT_POSTGRESQL_DB_PORT/$OPENSHIFT_APP_NAME --yes
   then
     echo "Unable to configure your Drupal installation"
     echo
@@ -89,11 +90,11 @@ $databases = array (
     'default' =>
     array (
       'database' => $src['OPENSHIFT_APP_NAME'],
-      'username' => $src['OPENSHIFT_MYSQL_DB_USERNAME'],
-      'password' => $src['OPENSHIFT_MYSQL_DB_PASSWORD'],
-      'host' => $src['OPENSHIFT_MYSQL_DB_HOST'],
-      'port' => $src['OPENSHIFT_MYSQL_DB_PORT'],
-      'driver' => 'mysql',
+      'username' => $src['OPENSHIFT_POSTGRESQL_DB_USERNAME'],
+      'password' => $src['OPENSHIFT_POSTGRESQL_DB_PASSWORD'],
+      'host' => $src['OPENSHIFT_POSTGRESQL_DB_HOST'],
+      'port' => $src['OPENSHIFT_POSTGRESQL_DB_PORT'],
+      'driver' => 'pgsql',
       'prefix' => '',
     ),
   ),
@@ -123,7 +124,7 @@ END
   client_result ""
   client_result "Drupal installed successfully."
   client_result ""
-  client_result "      Drupal admin login: admin"
+  client_result "   Drupal admin login: admin"
   client_result "   Drupal admin password: $admin_pwd"
   client_result ""
   client_result "Don't forget to change your drupal admin password!"
